name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: maven:3-eclipse-temurin-17

    steps:
    - name: Build with Maven
      run: mvn clean test
